[workspace]
members = [
    "crates/agent-lab-cli",
    "crates/agent-lab-core",
    "crates/agent-lab-driver-protocol",
    "crates/agent-lab-nushell-mcp",
    "crates/agent-lab-web",
]
resolver = "2"

[workspace.package]
edition = "2024"
publish = false
version = "0.0.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
